server:
  port: 8008

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL:jdbc:h2:mem:anywr}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
  liquibase:
    change-log: classpath:/db/master.xml
    enabled: ${LIQUIBASE_ENABLE:false}
    drop-first: ${LIQUIBASE_DROOP_FIRST:false}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect


app:
  token:
    key: ${TOKEN_KEY:4226452948404D635166546A576E5A7234753778214125442A462D4A614E6452}
    expiration: ${TOKEN_EXPIRATION:84000}